server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        autoindex on;  # Enables directory listing (Optional)
    }

    error_page 403 =404 /404.html;
}
